### ISSUE TITLE
[Bug]: mce::Image is not updated to 1.20.5x

### ISSUE THREAD

**Issue by FloppyDolphin57** [LiteLDev/LiteLoader#1410] opened 2023-12-20 21:04 UTC
### Describe the bug

Title

### To Reproduce

.

### Expected behavior

.

**Comment by OEOTYAN** [comment] 2023-12-21 02:45
Thanks for the report, but this issue is a duplicate of #1409 .

**Closed as not planned by OEOTYAN** 2023-12-21 02:45 UTC
Labels: duplicate

**Comment by FloppyDolphin57** [comment] 2023-12-21 16:38
> Thanks for the report, but this issue is a duplicate of #1409 .

Is there some place I can get in contact with you? Such as discord or telegram.

**Comment by Intoprelised** [comment] 2023-12-22 00:09
me too

**Comment by OEOTYAN** [comment] 2023-12-22 02:21
Theoretically, you could @OEOTYAN in LL's discord server, but I probably won't be checking that information very often, and it's probably better to communicate with the other main maintainers.
